const news = [
  {
    cid: 'culture',
    source: {
      id: 'engadget',
      name: 'Engadget',
    },
    author: 'Wirecutter',
    title: "Wirecutter's best deals: Save $300 on Apple's 15-inch MacBook Pro with Touch Bar",
    description: "This post was done in partnership with Wirecutter. When readers choose to buy Wirecutter's independently chosen editorial picks, it may earn affiliate commissions that support its work. Read Wirecutter's continuously updated list of deals here. Sony STR-DH190…",
    url: 'https://www.engadget.com/2019/03/07/wirecutters-best-deals-apple-macbook-pro-touch-bar-sale/',
    urlToImage: 'https://o.aolcdn.com/images/dims?thumbnail=1200%2C630&quality=80&image_uri=https%3A%2F%2Fo.aolcdn.com%2Fimages%2Fdims%3Fresize%3D2000%252C2000%252Cshrink%26image_uri%3Dhttps%253A%252F%252Fs.yimg.com%252Fos%252Fcreatr-uploaded-images%252F2019-03%252F22befef0-4112-11e9-bea4-f38461ec0d97%26client%3Da1acac3e1b3290917d92%26signature%3De549d04215d725e8bd4b31e22c30dd4a26132160&client=amp-blogside-v2&signature=6aad8b1c95f7d70550815f62adaaa6908cbfe4d7',
    publishedAt: '2019-03-07T20:30:00Z',
    content: "Street price: $150; deal price: $128\r\nDown to $128 from a typical price of $150, this is a nice deal on a basic but comparatively feature-rich receiver. This model isn't intended to be used as an AV surround option, but rather as a receiver meant for a stereo… [+5099 chars]",
  },
  {
    cid: 'culture',
    source: {
      id: 'the-verge',
      name: 'The Verge',
    },
    author: 'Sam Byford',
    title: 'The best Chinese phones Americans can’t buy',
    description: 'The American smartphone market is an increasingly boring place to be. You have Apple and Samsung at the top, LG in a distant third, then Motorola and maybe the occasional wildcard option like Google and OnePlus. You could be forgiven for having lost interest …',
    url: 'https://www.theverge.com/2019/3/7/18254348/the-best-chinese-phones-not-available-us',
    urlToImage: 'https://cdn.vox-cdn.com/thumbor/BYwoQxtOEYJj5NueCkVY0Or435c=/0x80:2040x1148/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/15944643/DSCF6931.jpg',
    publishedAt: '2019-03-07T12:30:00Z',
    content: '2019 edition The American smartphone market is an increasingly boring place to be. You have Apple and Samsung at the top, LG in a distant third, then Motorola, and maybe the occasional wildcard option like Google and OnePlus collectively making up less than t… [+9146 chars]',
  },
  {
    cid: 'tech',
    source: {
      id: 'techcrunch',
      name: 'TechCrunch',
    },
    author: 'Eric Peckham',
    title: 'Podcasts, smart speakers soar as social media stalls, based on new survey',
    description: 'The 2019 edition of a popular annual survey shows usage of social media by Americans is stalling while ownership of smart speakers and tablets has soared over the last year, as has consumer engagement with podcasts. The results are promising for Amazon and Sp…',
    url: 'http://techcrunch.com/2019/03/06/podcasts-smart-speakers-soar-as-social-media-stalls-based-on-new-survey/',
    urlToImage: 'https://techcrunch.com/wp-content/uploads/2015/11/shutterstock_226042204.jpg?w=600',
    publishedAt: '2019-03-07T03:23:14Z',
    content: 'The 2019 edition of a popular annual survey shows usage of social media by Americans is stalling while ownership of smart speakers and tablets has soared over the last year, as has consumer engagement with podcasts. The results are promising for Amazon and Sp… [+5004 chars]',
  },
  {
    cid: 'tech',
    source: {
      id: 'techcrunch',
      name: 'TechCrunch',
    },
    author: 'Rita Liao',
    title: 'Huawei is suing the the US government over “unconstitutional” equipment ban',
    description: 'Huawei has decided to go on the legal offence against the United States government after defending itself against alleged espionage and bank frauds linked to American sanctions on Iran. During a press conference late Wednesday, Huawei announced that it has fi…',
    url: 'http://techcrunch.com/2019/03/06/huawei-sues-us-government/',
    urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/03/Screen-Shot-2019-03-07-at-10.30.18-AM.png?w=694',
    publishedAt: '2019-03-07T02:34:01Z',
    content: 'Huawei has decided to go on the legal offence against the United States government after defending itself against alleged espionage and bank frauds linked to American sanctions on Iran. During a press conference late Wednesday, Huawei announced that it has fi… [+2507 chars]',
  },
  {
    cid: 'economy',
    source: {
      id: null,
      name: 'Gizmodo.com',
    },
    author: 'David Nield',
    title: 'USB4 is Going to Revolutionize the USB Standard All Over Again: What You Need to Know',
    description: 'It’s that time again—another USB standard is upon us, ready to upgrade your device’s ports and cabling in the coming years. Here we’re going to explain everything you need to know about USB4, including the speed improvements in the pipeline and the new capabi…',
    url: 'https://gizmodo.com/usb4-is-going-to-revolutionize-the-usb-standard-all-ove-1833059622',
    urlToImage: 'https://i.kinja-img.com/gawker-media/image/upload/s--PGhSRZ8A--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/lnmsdj4vrat9cbotxyab.jpg',
    publishedAt: '2019-03-07T15:15:00Z',
    content: 'Its that time againanother USB standard is upon us, ready to upgrade your devices ports and cabling in the coming years. Here were going to explain everything you need to know about USB4, including the speed improvements in the pipeline and the new capabiliti… [+4934 chars]',
  },
  {
    cid: 'economy',
    source: {
      id: null,
      name: 'Gizmodo.com',
    },
    author: 'Adam Clark Estes',
    title: 'How to Play PS4 on Your iPhone From Your Bathroom (And Other Places Too)',
    description: 'You can now completely control your Playstation 4 with an iOS device anywhere there’s internet thanks to a free, new PS4 Remote Play app. The new feature comes through a system software update for PS4, which is also free. After spending a few minutes acquirin…',
    url: 'https://gizmodo.com/how-to-play-ps4-on-your-iphone-from-your-bathroom-and-1833123458',
    urlToImage: 'https://i.kinja-img.com/gawker-media/image/upload/s--E_ZqAlI9--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/tzq3orecic3hipa8ol4y.jpg',
    publishedAt: '2019-03-07T16:40:00Z',
    content: 'You can now completely control your Playstation 4 with an iOS device anywhere theres internet thanks to a free, new PS4 Remote Play app. The new feature comes through a system software update for PS4, which is also free. After spending a few minutes acquiring… [+3937 chars]',
  },
  {
    cid: 'car',
    source: {
      id: null,
      name: 'Gizmodo.com',
    },
    author: 'Alex Cranz',
    title: 'You Are Not Ready For HoloLens 2',
    description: 'Microsoft figured it out. Tuesday I got my first opportunity to try out the HoloLens 2, and after slipping it over my head and taking a quick moment to calibrate the eye tracking, I was instantly able to move around the room and interact with objects crafted …',
    url: 'https://gizmodo.com/you-are-not-ready-for-hololens-2-1833109060',
    urlToImage: 'https://i.kinja-img.com/gawker-media/image/upload/s--U9-ZACSo--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/lzfvitzdkxrg9hycz2ps.jpg',
    publishedAt: '2019-03-07T16:27:00Z',
    content: 'Microsoft figured it out. Tuesday I got my first opportunity to try out the HoloLens 2, and after slipping it over my head and taking a quick moment to calibrate the eye tracking, I was instantly able to move around the room and interact with objects crafted … [+6249 chars]',
  },
  {
    cid: 'car',
    source: {
      id: 'mashable',
      name: 'Mashable',
    },
    author: 'Marcus Gilmer',
    title: "Tim Cook new Twitter name calls out Trump's 'Tim Apple' flub",
    description: "If you can say one thing about Apple CEO, it's that he has a great sense of humor. Cook has changed his Twitter name from \"Tim Cook\" (pretty obvious) to \"Tim ,\" seemingly in homage to President Donald Trump's flub on Wednesday when he called him \"Tim Apple\" …",
    url: 'https://mashable.com/article/tim-cook-apple-twitter-bio-change/',
    urlToImage: 'https://mondrian.mashable.com/2019%252F03%252F07%252F90%252F1d939a66e4544fdfbe37740c62a1440c.67a6f.png%252F1200x630.png?signature=bPihhjCaBk59O8BmlulXLsl55os=',
    publishedAt: '2019-03-07T18:37:40Z',
    content: "If you can say one thing about Apple CEO, it's that he has a great sense of humor. \r\nCook has changed his Twitter name from \"Tim Cook\" (pretty obvious) to \"Tim ,\" seemingly in homage to President Donald Trump's flub on Wednesday when he called him \"Tim Apple\"… [+776 chars]",
  },
  {
    cid: 'health',
    source: {
      id: 'mashable',
      name: 'Mashable',
    },
    author: 'Leah Stodart',
    title: 'The newest 12.9-inch iPad Pro is $99 off — its lowest price ever on Amazon',
    description: "\"Lowest price on Amazon ever\" is always pretty exciting. But when it's referring to an Apple product, you do more than watch — right after you ensure that you're not dreaming, of course. The newest 12.9-inch Apple iPad Pro (256 GB) is $99 off at just $1,049.9…",
    url: 'https://mashable.com/shopping/deal-march-7-apple-ipad-pro/',
    urlToImage: 'https://mondrian.mashable.com/2019%252F03%252F07%252Fc1%252F88192048a1c743939dff4cc81bf422d6.bb1c0.png%252F1200x630.png?signature=dRzC5B2uCZ5ZRCV3ORb0dWpB-14=',
    publishedAt: '2019-03-07T15:51:08Z',
    content: "\"Lowest price on Amazon ever\" is always pretty exciting. \r\nBut when it's referring to an Apple product, you do more than watch  right after you ensure that you're not dreaming, of course.\r\nThe newest 12.9-inch Apple iPad Pro (256 GB) is $99 off at just $1,049… [+1180 chars]",
  },
  {
    cid: 'health',
    source: {
      id: 'mashable',
      name: 'Mashable',
    },
    author: 'Laura Byager',
    title: "Phoebe Waller-Bridge acts like a dork in front of Meryl Streep, proves she's one of us",
    description: 'None of us really know how we would behave if we suddenly found ourselves face-to-face with with a real A-list Hollywood movie star. Writer and creator of play-turned-tv show Fleabag told Stephen Colbert on The Late Show, that when she first interacted with Q…',
    url: 'https://mashable.com/video/phoebe-waller-bridge-meryl-streep-colbert/',
    urlToImage: 'https://mondrian.mashable.com/2019%252F03%252F07%252Feb%252Fd8c07234edcd475aa35175fb9ddcd838.97dd0.jpg%252F1200x630.jpg?signature=1j0Ze_Wo9RqMtKOEEmFp6GYeiwY=',
    publishedAt: '2019-03-07T09:59:57Z',
    content: 'None of us really know how we would behave if we suddenly found ourselves face-to-face with with a real A-list Hollywood movie star. \r\nWriter and creator of play-turned-tv show Fleabag told Stephen Colbert on The Late Show, that when she first interacted with… [+426 chars]',
  },
  {
    cid: 'music',
    source: {
      id: 'mashable',
      name: 'Mashable',
    },
    author: 'Johnny Lieu',
    title: "Brie Larson and Samuel L. Jackson test their friendship on 'Carpool Karaoke'",
    description: 'Captain Marvel co-stars Brie Larson and Samuel L. Jackson have said they are pretty good pals. But even the best of friends tell the odd lie to each other, and the pair put it to the polygraph test in an episode of Carpool Karaoke, as previewed during The Lat…',
    url: 'https://mashable.com/video/brie-larson-samuel-jackson-carpool-karaoke/',
    urlToImage: 'https://mondrian.mashable.com/2019%252F03%252F07%252F4e%252Fd5e55accf8c04c759bff37ad7c3765a2.26d76.png%252F1200x630.png?signature=5JkyuAc8b8_hPWi6xAorybgY6aI=',
    publishedAt: '2019-03-07T05:00:28Z',
    content: 'Captain Marvel co-stars Brie Larson and Samuel L. Jackson have said they are pretty good pals.\r\nBut even the best of friends tell the odd lie to each other, and the pair put it to the polygraph test in an episode of Carpool Karaoke, as previewed during The La… [+250 chars]',
  },
  {
    cid: 'music',
    source: {
      id: 'mashable',
      name: 'Mashable',
    },
    author: 'PCMag',
    title: '15 Hulu tips for streaming TV fans',
    description: "If you're a cord cutter or want to be, but can't abandon network TV, you need Hulu. The service is best known for streaming shows the day after they air, specifically shows from a few of the five major networks—ABC, NBC, and Fox. (CBS has its own streaming se…",
    url: 'https://mashable.com/article/15-hulu-tips-for-streaming-tv-fans/',
    urlToImage: 'https://mondrian.mashable.com/2019%252F03%252F07%252F36%252F0578b36f5fd94562af3618332ea26d72.d7ef4.jpg%252F1200x630.jpg?signature=jwEUF3JnF_CKdNsNJhPiWgxvhC0=',
    publishedAt: '2019-03-07T15:59:50Z',
    content: "If you're a cord cutter or want to be, but can't abandon network TV, you need Hulu. The service is best known for streaming shows the day after they air, specifically shows from a few of the five major networksABC, NBC, and Fox. (CBS has its own streaming ser… [+10302 chars]",
  },
  {
    cid: 'photograph',
    source: {
      id: 'the-new-york-times',
      name: 'The New York Times',
    },
    author: 'CADE METZ',
    title: 'Jerry Merryman, Co-Inventor of the Pocket Calculator, Dies at 86',
    description: 'Jerry Merryman, right, with a fellow co-inventor of the pocket calculator, Jack Kilby, at the American Computer Museum in Bozeman, Mont., in 1997. The third inventor was James Van Tassel. Mr. Kilby received a Nobel Prize for his work on integrated circuity.',
    url: 'https://www.nytimes.com/2019/03/07/obituaries/jerry-merryman-dead.html',
    urlToImage: 'https://static01.nyt.com/images/2019/03/07/obituaries/07merryman/07merryman-facebookJumbo.jpg',
    publishedAt: '2019-03-07T20:21:45Z',
    content: 'He, Mr. Kilby and Mr. Van Tassel initially built a prototype, which spanned an entire room at their Texas Instruments lab. Then, over the next two years, they packed the same circuit design into a hand-held casing using microchips.\r\nThe device had 18 keys, an… [+1338 chars]',
  },
  {
    cid: 'photograph',
    source: {
      id: 'cnn',
      name: 'CNN',
    },
    author: null,
    title: 'Trump calls Apple CEO by wrong name',
    description: "Late-night comics poke fun at President Donald Trump's numbers in the polls and his attempts to get Ivanka Trump security clearance.",
    url: 'https://www.cnn.com/videos/media/2019/03/07/late-night-laughs-trump-tough-week-sot-newday-vpx.cnn',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/180604210214-cnnmoney-donald-trump-tim-cook-super-tease.jpg',
    publishedAt: '2019-03-07T14:03:41Z',
    content: null,
  },
  {
    cid: 'time control',
    source: {
      id: 'ars-technica',
      name: 'Ars Technica',
    },
    author: 'Ars Staff',
    title: 'Dealmaster: Expand your laptop with our recommended USB-C travel hub, now $24',
    description: 'Plus deals on PS4 Pro, 4K TVs, Bose Bluetooth speakers, iPads, and more.',
    url: 'https://arstechnica.com/staff/2019/03/dealmaster-expand-your-laptop-with-our-recommended-usb-c-travel-hub-now-24/',
    urlToImage: 'https://cdn.arstechnica.net/wp-content/uploads/2019/03/0307-hero-760x380.png',
    publishedAt: '2019-03-07T19:18:19Z',
    content: "4 with 4 posters participating\r\nGreetings, Arsians! Courtesy of our friends at TechBargains, we have another round of deals to share. Today's list is headlined by a deal on Vava's USB-C Hub, which is currently down to $24 with a 10 percent on-site coupon and … [+6430 chars]",
  },
  {
    cid: 'time control',
    source: {
      id: 'ars-technica',
      name: 'Ars Technica',
    },
    author: 'Kyle Orland',
    title: 'With Rape Day ban, Steam shows it’s not as “hands off” as it claims',
    description: 'Lack of guidelines leads to capricious, reactive responses to controversy.',
    url: 'https://arstechnica.com/gaming/2019/03/with-rape-day-ban-steam-shows-its-not-as-hands-off-as-it-claims/',
    urlToImage: 'https://cdn.arstechnica.net/wp-content/uploads/2019/03/rday-760x380.jpg',
    publishedAt: '2019-03-07T15:43:50Z',
    content: "Rape Day offered on the game's Steam page before it was taken down.\"/&gt;\r\n Enlarge/ One of the few safe-for-work images of Rape Day offered on the game's Steam page before it was taken down.\r\n4 with 4 posters participating, including story author\r\nSince last… [+8116 chars]",
  },
  {
    cid: 'ideas',
    source: {
      id: 'ars-technica',
      name: 'Ars Technica',
    },
    author: 'Samuel Axon',
    title: 'Zuckerberg: Facebook will shift focus to private networks instead of open ones',
    description: 'Facebook will focus on messaging platforms like WhatsApp—with big changes.',
    url: 'https://arstechnica.com/gadgets/2019/03/zuckerberg-facebook-will-shift-focus-to-private-networks-instead-of-open-ones/',
    urlToImage: 'https://cdn.arstechnica.net/wp-content/uploads/2015/05/zuckerberg-internet.org_-640x215.png',
    publishedAt: '2019-03-07T14:33:51Z',
    content: 'Mark Zuckerberg discussing issues with an audience. (This time he used a blog post, though.)\r\n12 with 12 posters participating\r\nOn Wednesday, Facebook CEO Mark Zuckerberg published a more-than-3,000-word blog post that seems to declare a major shift in Facebo… [+9513 chars]',
  },
  {
    cid: 'ideas',
    source: {
      id: 'reuters',
      name: 'Reuters',
    },
    author: 'Andrew Osborn',
    title: 'For Kremlin, Ukrainian election a choice between lesser of three evils',
    description: 'Before Russia annexed Crimea and backed separatists in east Ukraine, Moscow had a Ukrainian president who did much of what it wanted. Now, as Ukraine readies to elect a new leader, none of the main candidates look that enticing to Russia.',
    url: 'https://www.reuters.com/article/us-ukraine-election-russia-idUSKCN1QO0H6',
    urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20190307&t=2&i=1363625803&w=1200&r=LYNXNPEF260BE',
    publishedAt: '2019-03-07T06:08:15Z',
    content: 'MOSCOW/KIEV (Reuters) - Before Russia annexed Crimea and backed separatists in east Ukraine, Moscow had a Ukrainian president who did much of what it wanted. Now, as Ukraine readies to elect a new leader, none of the main candidates look that enticing to Russ… [+5324 chars]',
  },
  {
    cid: 'culture',
    source: {
      id: null,
      name: 'Androidcentral.com',
    },
    author: 'Alex Smith',
    title: 'Step onto the app-enabled Body Cardio Smart Scale at one of its best prices',
    description: "This scale syncs automatically with the Health Mate app to keep your stats current. How's that New Year's resolution coming? Hopefully you've been keeping up with your goals, but if you're looking to make things a bit easier, consider grabbing the Withings Bo…",
    url: 'https://www.androidcentral.com/thrifter-deal-withings-body-cardio-wi-fi-smart-scale',
    urlToImage: 'https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/article_images/2019/03/withings-body-cardio-scale-main.jpg?itok=lwvMQku',
    publishedAt: '2019-03-07T16:49:48Z',
    content: "How's that New Year's resolution coming? Hopefully you've been keeping up with your goals, but if you're looking to make things a bit easier, consider grabbing the Withings Body Cardio Wi-Fi Smart Scale while it's on sale at Newegg Flash. For the next few day… [+1049 chars]",
  },
  {
    cid: 'tech',
    source: {
      id: null,
      name: 'Androidcentral.com',
    },
    author: 'Anonymous',
    title: 'Bring your home lighting into the future with $10 off LIFX Smart multicolor LED bulbs',
    description: "Smarten up your home by saving on these bulbs. Amazon is offering the LIFX A19 Multicolor Smart LED Light Bulb for $39.99. That's around $10 off the average price for this smart bulb and is matching a one-day deal at Best Buy. These light bulbs are compatible…",
    url: 'https://www.androidcentral.com/thrifter-deal-lifx-wi-fi-smart-multicolor-led-light-bulb',
    urlToImage: 'https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/lifx-bulb_0-10z3-10z3-10z3.jpg?itok=kW-YQmgy',
    publishedAt: '2019-03-07T10:06:21Z',
    content: "Amazon is offering the LIFX A19 Multicolor Smart LED Light Bulb for $39.99. That's around $10 off the average price for this smart bulb and is matching a one-day deal at Best Buy.\r\nThese light bulbs are compatible with Alexa, Google Assistant, and Apple HomeK… [+531 chars]",
  },
];

module.exports = news;
